# Generated by Django 3.1.7 on 2021-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roll',
            field=models.CharField(choices=[('D', 'Developer'), ('T', 'Tester')], default=22, max_length=1),
            preserve_default=False,
        ),
    ]
