# Generated by Django 3.1.7 on 2021-04-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20210409_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='skill',
        ),
    ]
