# Generated by Django 3.1.7 on 2021-04-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_auto_20210410_1254'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skills',
            table='emp_skill',
        ),
    ]
