# Generated by Django 3.1.7 on 2021-04-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_auto_20210415_1409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
    ]
