# Generated by Django 3.1.7 on 2021-04-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_auto_20210417_1030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skill',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
